/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Liveness check. The launcher uses `app == "scrappy-records"` to recognise a running copy
         *     of this app on the port.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Students
         * @description Students sorted by name, each with their current fee and balance.
         */
        get: operations["listStudents"];
        put?: never;
        /**
         * Create Student
         * @description Create a student. Also records their first fee change at `joined_month`.
         */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student
         * @description A student with their fee history and month-by-month ledger.
         */
        get: operations["getStudent"];
        put?: never;
        post?: never;
        /**
         * Delete Student
         * @description Hard delete. Their fee changes and payments are deleted too.
         */
        delete: operations["deleteStudent"];
        options?: never;
        head?: never;
        /**
         * Update Student
         * @description Partial update. A new fee (`monthly_fee_paise`) is recorded as a fee change from
         *     `fee_effective_month` (default: the current month).
         */
        patch: operations["updateStudent"];
        trace?: never;
    };
    "/api/students/{student_id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return Student
         * @description A student who left is coming again from `from_month`. The months they were away get a
         *     0 fee (never owed), their fee carries on from `from_month`, and `left_month` is cleared,
         *     all at once.
         */
        post: operations["returnStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/fee-changes/{fee_change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Fee Change
         * @description Remove a fee change that hasn't started yet. Never the first (joining) fee.
         */
        delete: operations["deleteFeeChange"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}/suggest-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Payment
         * @description The oldest unpaid or partial month up to now and what's left on it; otherwise the next
         *     month that isn't fully paid (usually next month) and what's left on it.
         */
        get: operations["suggestPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Payments
         * @description Every payment matching the filters, with the student's name and where its money went
         *     (its own month, other unpaid months, or credit).
         */
        get: operations["listPayments"];
        put?: never;
        /** Create Payment */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        /** Delete Payment */
        delete: operations["deletePayment"];
        options?: never;
        head?: never;
        /**
         * Update Payment
         * @description Partial update. Only fields that are sent change.
         */
        patch: operations["updatePayment"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Summary, yet-to-pay, backlog and overpaid lists for one month.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacklogItem
         * @description A student with Unpaid or Partial months before M.
         */
        BacklogItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Months
             * @description Oldest first.
             */
            months: components["schemas"]["BacklogMonth"][];
            /**
             * Total Owed Paise
             * @description Amount in paise, more than 0.
             */
            total_owed_paise: number;
            /**
             * Credit Paise
             * @description The student's credit (see StudentRead.credit_paise). Almost always 0 here: extra money covers unpaid months first.
             */
            credit_paise: number;
        };
        /** BacklogMonth */
        BacklogMonth: {
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Logged for this month, as typed.
             */
            paid_paise: number;
            /**
             * Covered By Credit Paise
             * @description Extra money from payments logged for other months that covers it.
             */
            covered_by_credit_paise: number;
            /**
             * Remaining Paise
             * @description Amount in paise, more than 0.
             */
            remaining_paise: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unpaid" | "partial";
        };
        /**
         * BalanceStatus
         * @description Overall standing of a student (PRD "Ledger rules", rule 6): `owes` if any due month is
         *     still short after extra money has covered what it can; else `credit` if some money wasn't
         *     needed by any month; else `up_to_date`.
         * @enum {string}
         */
        BalanceStatus: "up_to_date" | "owes" | "credit";
        /**
         * CreditMoveItem
         * @description Extra money from a payment logged for one month (`from_month`) that covers another
         *     (`to_month`). On M's dashboard, one of the two is M.
         */
        CreditMoveItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /** Payment Id */
            payment_id: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * From Month
             * @description The month the payment was logged for.
             * @example 2026-10
             */
            from_month: string;
            /**
             * To Month
             * @description The month its extra money covers.
             * @example 2026-10
             */
            to_month: string;
            /**
             * Amount Paise
             * @description Amount in paise, more than 0.
             */
            amount_paise: number;
            /**
             * Payment Amount Paise
             * @description The whole payment, as typed.
             */
            payment_amount_paise: number;
            /**
             * Payment Pays Until
             * @description The latest month the payment pays (so a screen can say 'pays up to …').
             * @example 2026-10
             */
            payment_pays_until: string;
            /**
             * Payment Needs Check
             * @description See PaymentRead.needs_check.
             */
            payment_needs_check: boolean;
        };
        /**
         * CreditSource
         * @description Extra money from one payment, logged for another month, that covers this month.
         */
        CreditSource: {
            /** Payment Id */
            payment_id: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * For Month
             * @description The month that payment was logged for.
             * @example 2026-10
             */
            for_month: string;
            /**
             * Amount Paise
             * @description How much of it covers this month.
             */
            amount_paise: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Month
             * @description The month shown (M).
             * @example 2026-10
             */
            month: string;
            /**
             * Current Month
             * @description The server's current month. Months after it aren't due yet.
             * @example 2026-10
             */
            current_month: string;
            summary: components["schemas"]["DashboardSummary"];
            /** Yet To Pay */
            yet_to_pay: components["schemas"]["YetToPayItem"][];
            /** Backlog */
            backlog: components["schemas"]["BacklogItem"][];
            /**
             * Overpaid
             * @description Months holding credit (money not used).
             */
            overpaid: components["schemas"]["OverpaidItem"][];
            /**
             * Credit Moves
             * @description Extra money moved out of M's payments, or into M from other months' payments. By student, then the month covered, then the payment's date.
             */
            credit_moves: components["schemas"]["CreditMoveItem"][];
        };
        /** DashboardSummary */
        DashboardSummary: {
            /**
             * Expected Paise
             * @description Expected for M from active students.
             */
            expected_paise: number;
            /**
             * Collected Paise
             * @description What pays M: payments logged for M, up to each fee, plus extra money from payments logged for other months that covers M (Σ paid_direct + covered_by_credit).
             */
            collected_paise: number;
            /**
             * Paid Ahead Paise
             * @description For a month after the current one: the same as collected_paise (what pays it ahead of time). 0 for the current month and earlier ones.
             */
            paid_ahead_paise: number;
            /**
             * Still Due Paise
             * @description What's left on M, after extra money, over students active in M.
             */
            still_due_paise: number;
            /**
             * Logged Paise
             * @description Every payment logged for M, as typed: the Payments page's total for M. collected = logged - sent_elsewhere - (kept as credit) + covered_by_credit.
             */
            logged_paise: number;
            /**
             * Covered By Credit Paise
             * @description The part of collected_paise that came from payments logged for other months.
             */
            covered_by_credit_paise: number;
            /**
             * Sent Elsewhere Paise
             * @description The part of logged_paise that paid other months (the rest above the fees is kept as credit).
             */
            sent_elsewhere_paise: number;
            /**
             * Not Fully Paid Count
             * @description Students unpaid or partial for M.
             */
            not_fully_paid_count: number;
            /**
             * Active Student Count
             * @description Students with a fee due in M: active in M, with a fee above 0.
             */
            active_student_count: number;
        };
        /**
         * ErrorResponse
         * @description Error body for 404 (and other non-validation errors): `detail` is a sentence.
         *
         *     422 responses use FastAPI's `HTTPValidationError` instead, where `detail` is a list of
         *     `{loc, msg, type}` items. Business-rule 422s raised by routers use the same list shape (see
         *     `app.errors.unprocessable`), so the UI handles one 422 format.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ExtraSent
         * @description Money paid above a month's fee that covers another month.
         */
        ExtraSent: {
            /**
             * To Month
             * @description The month it covers.
             * @example 2026-10
             */
            to_month: string;
            /**
             * Amount Paise
             * @description Amount in paise, more than 0.
             */
            amount_paise: number;
        };
        /** FeeChangeRead */
        FeeChangeRead: {
            /** Id */
            id: number;
            /**
             * Effective Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            effective_month: string;
            /**
             * Amount Paise
             * @description Amount in paise, 0 or more.
             */
            amount_paise: number;
            /** @description `fee`: set by the owner (₹0 is a month off or a free place). `away`: the ₹0 for the months away, written by coming back after leaving. */
            kind: components["schemas"]["FeeKind"];
        };
        /**
         * FeeKind
         * @description What a fee change is. `fee`: a fee the owner set (₹0 means a month off or a free place).
         *     `away`: the ₹0 for the months away, written by coming back after leaving (PRD ledger rule
         *     11), and managed by the app: cleaned up when the left month changes or they come back
         *     again.
         * @enum {string}
         */
        FeeKind: "fee" | "away";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * App
             * @constant
             */
            app: "scrappy-records";
            /**
             * Version
             * @example 0.1.0
             */
            version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * LedgerMonth
         * @description One row of a student's month-by-month ledger, after extra money has been handed out
         *     (PRD ledger rule 10). For every month:
         *     `paid_paise = paid_direct_paise + Σ extra_sent + extra_unused_paise`, and
         *     `paid_direct_paise + covered_by_credit_paise + remaining_paise = expected_paise`.
         */
        LedgerMonth: {
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Everything logged for this month, exactly as typed.
             */
            paid_paise: number;
            /**
             * Paid Direct Paise
             * @description The part of paid_paise that pays this month: at most its fee.
             */
            paid_direct_paise: number;
            /**
             * Covered By Credit Paise
             * @description Extra money from payments logged for other months that pays this month (the sum of credit_sources).
             */
            covered_by_credit_paise: number;
            /**
             * Credit Sources
             * @description Where covered_by_credit_paise came from, in the order it was handed out.
             */
            credit_sources: components["schemas"]["CreditSource"][];
            /**
             * Extra Sent
             * @description Where the money paid for this month above its fee went, one entry per month covered, oldest first.
             */
            extra_sent: components["schemas"]["ExtraSent"][];
            /**
             * Extra Unused Paise
             * @description Money paid for this month that no month needed: credit.
             */
            extra_unused_paise: number;
            /**
             * Remaining Paise
             * @description What's still left: max(0, expected - paid_direct - covered_by_credit).
             */
            remaining_paise: number;
            /**
             * Excess Paise
             * @description max(0, paid - expected): what was paid for this month above its fee (extra_sent plus extra_unused_paise).
             */
            excess_paise: number;
            status: components["schemas"]["MonthStatus"];
            /**
             * Is Due
             * @description True for months up to and including the current month. What pays a later month is 'paid ahead'.
             */
            is_due: boolean;
        };
        /**
         * MonthStatus
         * @description Status of one student for one month (PRD "Ledger rules", rule 4), counting what was paid
         *     for the month itself plus extra money from other payments that covers it (rule 10).
         *
         *     - `paid`: fully paid. It was paid **with credit** when `covered_by_credit_paise > 0`.
         *     - `partial`, `unpaid`: some, or none, of the fee is covered.
         *     - `overpaid`: some of the money paid for this month wasn't needed by any month, so it is
         *       credit (`extra_unused_paise > 0`).
         *     - `not_applicable`: no fee, and none of this month's money is left as credit.
         * @enum {string}
         */
        MonthStatus: "paid" | "partial" | "unpaid" | "overpaid" | "not_applicable";
        /**
         * OverpaidItem
         * @description A student-month up to M (or later, from the current month on) holding money that no
         *     month needed: credit (`extra_unused_paise > 0`).
         */
        OverpaidItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Amount in paise, more than 0.
             */
            paid_paise: number;
            /**
             * Excess Paise
             * @description max(0, paid - expected), as on LedgerMonth.
             */
            excess_paise: number;
            /**
             * Extra Unused Paise
             * @description The part of it no month needed: credit.
             */
            extra_unused_paise: number;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Student Id */
            student_id: number;
            /**
             * Amount Paise
             * @description Amount in paise: more than 0, at most 100000000 (₹10,00,000).
             */
            amount_paise: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * For Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            for_month: string;
            method: components["schemas"]["PaymentMethod"];
            /** Note */
            note?: string | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "upi" | "cash" | "other";
        /**
         * PaymentRead
         * @description A payment exactly as typed, plus where its money went (PRD ledger rule 10):
         *     `amount_paise = paid_direct_paise + Σ extra_sent + extra_unused_paise`.
         */
        PaymentRead: {
            /** Id */
            id: number;
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /**
             * Amount Paise
             * @description Amount in paise, more than 0.
             */
            amount_paise: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * For Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            for_month: string;
            method: components["schemas"]["PaymentMethod"];
            /** Note */
            note: string | null;
            /**
             * Paid Direct Paise
             * @description The part that pays for_month itself (at most what was left of its fee).
             */
            paid_direct_paise: number;
            /**
             * Needs Check
             * @description Worth a glance, in case of a typo: it pays 3 or more other months, or it's 3 times its month's fee or more.
             */
            needs_check: boolean;
            /**
             * Extra Sent
             * @description The rest, covering other unpaid months, oldest first.
             */
            extra_sent: components["schemas"]["ExtraSent"][];
            /**
             * Extra Unused Paise
             * @description What no month needed: credit.
             */
            extra_unused_paise: number;
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
        };
        /**
         * PaymentSort
         * @enum {string}
         */
        PaymentSort: "paid_on" | "for_month" | "amount" | "student" | "method";
        /**
         * PaymentUpdate
         * @description Partial update. Only fields that are sent change.
         */
        PaymentUpdate: {
            /** Student Id */
            student_id?: number | null;
            /** Amount Paise */
            amount_paise?: number | null;
            /** Paid On */
            paid_on?: string | null;
            /** For Month */
            for_month?: string | null;
            method?: components["schemas"]["PaymentMethod"] | null;
            /** Note */
            note?: string | null;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** StudentCreate */
        StudentCreate: {
            /** Name */
            name: string;
            /**
             * Monthly Fee Paise
             * @description Monthly fee in paise: 0 or more, at most 100000000 (₹10,00,000).
             */
            monthly_fee_paise: number;
            /**
             * Joined Month
             * @description First month they owe.
             * @example 2026-10
             */
            joined_month: string;
            /** Phone */
            phone?: string | null;
            /** Guardian Name */
            guardian_name?: string | null;
            /** Batch Label */
            batch_label?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Left Month
             * @description Last month they owe. Setting it archives the student.
             */
            left_month?: string | null;
        };
        /** StudentDetail */
        StudentDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Guardian Name */
            guardian_name: string | null;
            /** Batch Label */
            batch_label: string | null;
            /**
             * Joined Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            joined_month: string;
            /** Left Month */
            left_month: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Is Active
             * @description True until the left month has passed (no left_month, or left_month is this month or later). False means Left (archived).
             */
            is_active: boolean;
            /**
             * Monthly Fee Paise
             * @description Fee in effect this month.
             */
            monthly_fee_paise: number;
            /**
             * Balance Paise
             * @description Net: all payments minus everything expected up to this month. For reference only: money paid ahead or paid twice can cancel out months still owed, so headlines use `status` and `owed_paise`.
             */
            balance_paise: number;
            /** @description `owes` if anything is owed for a due month (`owed_paise` > 0); otherwise `credit` if some money wasn't needed by any month (`credit_paise` > 0); otherwise `up_to_date`. */
            status: components["schemas"]["BalanceStatus"];
            /**
             * Owed Paise
             * @description Still owed: the sum of what's left on every due month (active months up to and including the current month), after extra money has covered the oldest months.
             */
            owed_paise: number;
            /**
             * Paid Ahead Paise
             * @description Money that pays months after the current month that they're still enrolled in: what was logged for them, up to each fee, plus extra money from other payments that covers them.
             */
            paid_ahead_paise: number;
            /**
             * Credit Paise
             * @description Money no month needed: what's left of the payments once each has paid its own month and covered every unpaid month it could (due months, then later ones up to left_month or 24 months ahead). The sum of the months' extra_unused_paise.
             */
            credit_paise: number;
            /** @description The first fee change after the month monthly_fee_paise is for, if any (so the UI can say "No fee until December 2026, then ₹1,000"). */
            next_fee_change: components["schemas"]["FeeChangeRead"] | null;
            /**
             * Tenure Months
             * @description How long they have been a student, in months. Still coming: whole months since joined_month (0 in the joining month or before). Left (left_month before the current month): the months enrolled, both ends counted (left_month - joined_month + 1).
             */
            tenure_months: number;
            /**
             * Current Month
             * @description The server's current month, which every number here is worked out for.
             * @example 2026-10
             */
            current_month: string;
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
            /**
             * Fee History
             * @description Oldest first.
             */
            fee_history: components["schemas"]["FeeChangeRead"][];
            /**
             * Months
             * @description From joined_month to the current month (or the last paid month, if later). Oldest first.
             */
            months: components["schemas"]["LedgerMonth"][];
            /** Payment Count */
            payment_count: number;
            /**
             * Total Paid Paise
             * @description Amount in paise, 0 or more.
             */
            total_paid_paise: number;
        };
        /**
         * StudentListFilter
         * @description `status` filter for `GET /api/students`. `left` means archived.
         * @enum {string}
         */
        StudentListFilter: "active" | "left" | "all";
        /**
         * StudentRead
         * @description A student as shown in lists, with their current fee and overall balance.
         */
        StudentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Guardian Name */
            guardian_name: string | null;
            /** Batch Label */
            batch_label: string | null;
            /**
             * Joined Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            joined_month: string;
            /** Left Month */
            left_month: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Is Active
             * @description True until the left month has passed (no left_month, or left_month is this month or later). False means Left (archived).
             */
            is_active: boolean;
            /**
             * Monthly Fee Paise
             * @description Fee in effect this month.
             */
            monthly_fee_paise: number;
            /**
             * Balance Paise
             * @description Net: all payments minus everything expected up to this month. For reference only: money paid ahead or paid twice can cancel out months still owed, so headlines use `status` and `owed_paise`.
             */
            balance_paise: number;
            /** @description `owes` if anything is owed for a due month (`owed_paise` > 0); otherwise `credit` if some money wasn't needed by any month (`credit_paise` > 0); otherwise `up_to_date`. */
            status: components["schemas"]["BalanceStatus"];
            /**
             * Owed Paise
             * @description Still owed: the sum of what's left on every due month (active months up to and including the current month), after extra money has covered the oldest months.
             */
            owed_paise: number;
            /**
             * Paid Ahead Paise
             * @description Money that pays months after the current month that they're still enrolled in: what was logged for them, up to each fee, plus extra money from other payments that covers them.
             */
            paid_ahead_paise: number;
            /**
             * Credit Paise
             * @description Money no month needed: what's left of the payments once each has paid its own month and covered every unpaid month it could (due months, then later ones up to left_month or 24 months ahead). The sum of the months' extra_unused_paise.
             */
            credit_paise: number;
            /** @description The first fee change after the month monthly_fee_paise is for, if any (so the UI can say "No fee until December 2026, then ₹1,000"). */
            next_fee_change: components["schemas"]["FeeChangeRead"] | null;
            /**
             * Tenure Months
             * @description How long they have been a student, in months. Still coming: whole months since joined_month (0 in the joining month or before). Left (left_month before the current month): the months enrolled, both ends counted (left_month - joined_month + 1).
             */
            tenure_months: number;
            /**
             * Current Month
             * @description The server's current month, which every number here is worked out for.
             * @example 2026-10
             */
            current_month: string;
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
        };
        /**
         * StudentReturn
         * @description Body of `POST /students/{id}/return`: a student who left is coming again (PRD ledger
         *     rule 11). The months between `left_month` and `from_month` get a 0 fee, so they are never
         *     owed; their fee carries on from `from_month`.
         */
        StudentReturn: {
            /**
             * From Month
             * @description The first month they owe again: after left_month, at most 24 months after the current month.
             * @example 2026-10
             */
            from_month: string;
            /**
             * Monthly Fee Paise
             * @description Their fee from from_month. Defaults to the fee their schedule has for that month, ignoring ₹0 fees left by an earlier return.
             */
            monthly_fee_paise?: number | null;
        };
        /**
         * StudentUpdate
         * @description Partial update. Only fields that are sent change.
         *
         *     To change the fee, send `monthly_fee_paise`, and optionally `fee_effective_month` (defaults
         *     to the current month). Earlier months keep their fee, and the new fee lasts until the next
         *     fee change already set after it, if any. Send `left_month: null` to un-archive a student
         *     as if they never left (every month since counts); `POST /students/{id}/return` instead
         *     skips the months they were away.
         *
         *     Edit rules. This model checks what it can on its own. The router checks the rest against the
         *     stored student and answers **422** in the standard validation shape (`app.errors`), never a
         *     500 from a database CHECK:
         *
         *     1. **Moving `joined_month`** moves the earliest fee change's `effective_month` with it, so
         *        the first owed month always has a fee. If the new joined month is on or after a later
         *        fee change, answer 422, because the earliest fee would disappear.
         *     2. **`fee_effective_month` before `joined_month`** (the new one if sent, else the stored
         *        one) → 422. A fee change for a month that already has one replaces its amount.
         *     3. **`left_month`** is checked against `joined_month` (the new one if sent, else the
         *        stored one): `left_month < joined_month` → 422.
         */
        StudentUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Guardian Name */
            guardian_name?: string | null;
            /** Batch Label */
            batch_label?: string | null;
            /** Notes */
            notes?: string | null;
            /** Joined Month */
            joined_month?: string | null;
            /** Left Month */
            left_month?: string | null;
            /** Monthly Fee Paise */
            monthly_fee_paise?: number | null;
            /**
             * Fee Effective Month
             * @description Month the new fee starts. Only with monthly_fee_paise. Defaults to now.
             */
            fee_effective_month?: string | null;
        };
        /**
         * SuggestedPayment
         * @description Prefill for the Log payment form (PRD "Ledger rules", rule 9). Never a month that is
         *     already fully paid, and never one outside the months the student is enrolled in.
         *
         *     - `owed`: the oldest month up to now that is Unpaid or Partial, and what's left on it.
         *     - `next_unpaid`: the first later month with a fee that isn't fully paid, and what's left on
         *       it. Months with a 0 fee are skipped.
         *     - `all_paid`: nothing left to pay; `for_month` and `amount_paise` are null.
         */
        SuggestedPayment: {
            /** For Month */
            for_month: string | null;
            /** Amount Paise */
            amount_paise: number | null;
            reason: components["schemas"]["SuggestionReason"];
        };
        /**
         * SuggestionReason
         * @description Why `SuggestedPayment` suggests what it does (PRD "Ledger rules", rule 9).
         * @enum {string}
         */
        SuggestionReason: "owed" | "next_unpaid" | "all_paid";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * YetToPayItem
         * @description A student active in M who is Unpaid or Partial for M.
         */
        YetToPayItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Logged for M, as typed.
             */
            paid_paise: number;
            /**
             * Covered By Credit Paise
             * @description Extra money from payments logged for other months that covers M.
             */
            covered_by_credit_paise: number;
            /**
             * Remaining Paise
             * @description Amount in paise, more than 0.
             */
            remaining_paise: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unpaid" | "partial";
            /**
             * Credit Paise
             * @description The student's credit (see StudentRead.credit_paise). Almost always 0 here: extra money covers unpaid months first.
             */
            credit_paise: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type BacklogItem = components['schemas']['BacklogItem'];
export type BacklogMonth = components['schemas']['BacklogMonth'];
export type BalanceStatus = components['schemas']['BalanceStatus'];
export type CreditMoveItem = components['schemas']['CreditMoveItem'];
export type CreditSource = components['schemas']['CreditSource'];
export type DashboardResponse = components['schemas']['DashboardResponse'];
export type DashboardSummary = components['schemas']['DashboardSummary'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type ExtraSent = components['schemas']['ExtraSent'];
export type FeeChangeRead = components['schemas']['FeeChangeRead'];
export type FeeKind = components['schemas']['FeeKind'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type LedgerMonth = components['schemas']['LedgerMonth'];
export type MonthStatus = components['schemas']['MonthStatus'];
export type OverpaidItem = components['schemas']['OverpaidItem'];
export type PaymentCreate = components['schemas']['PaymentCreate'];
export type PaymentMethod = components['schemas']['PaymentMethod'];
export type PaymentRead = components['schemas']['PaymentRead'];
export type PaymentSort = components['schemas']['PaymentSort'];
export type PaymentUpdate = components['schemas']['PaymentUpdate'];
export type SortOrder = components['schemas']['SortOrder'];
export type StudentCreate = components['schemas']['StudentCreate'];
export type StudentDetail = components['schemas']['StudentDetail'];
export type StudentListFilter = components['schemas']['StudentListFilter'];
export type StudentRead = components['schemas']['StudentRead'];
export type StudentReturn = components['schemas']['StudentReturn'];
export type StudentUpdate = components['schemas']['StudentUpdate'];
export type SuggestedPayment = components['schemas']['SuggestedPayment'];
export type SuggestionReason = components['schemas']['SuggestionReason'];
export type ValidationError = components['schemas']['ValidationError'];
export type YetToPayItem = components['schemas']['YetToPayItem'];
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listStudents: {
        parameters: {
            query?: {
                /** @description `active` (default: not left yet, i.e. no left month or it is this month or later), `left` (the left month has passed) or `all`. */
                status?: components["schemas"]["StudentListFilter"];
                /** @description Case-insensitive search on name, phone, guardian. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returnStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentReturn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteFeeChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
                fee_change_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such student or fee change */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedPayment"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: {
                /** @description Only this student's payments. */
                student_id?: number | null;
                /** @description Only payments for this month (`for_month`). */
                month?: string | null;
                /** @description Case-insensitive search on student name and note. */
                q?: string | null;
                sort?: components["schemas"]["PaymentSort"];
                order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                /** @description Defaults to the current month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
