/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Liveness check. The launcher uses `app == "scrappy-records"` to recognise a running copy
         *     of this app on the port.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Students
         * @description Students sorted by name, each with their current fee and balance.
         */
        get: operations["listStudents"];
        put?: never;
        /**
         * Create Student
         * @description Create a student. Also records their first fee change at `joined_month`.
         */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student
         * @description A student with their fee history and month-by-month ledger.
         */
        get: operations["getStudent"];
        put?: never;
        post?: never;
        /**
         * Delete Student
         * @description Hard delete. Their fee changes and payments are deleted too.
         */
        delete: operations["deleteStudent"];
        options?: never;
        head?: never;
        /**
         * Update Student
         * @description Partial update. A new fee (`monthly_fee_paise`) is recorded as a fee change from
         *     `fee_effective_month` (default: the current month).
         */
        patch: operations["updateStudent"];
        trace?: never;
    };
    "/api/students/{student_id}/suggest-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Payment
         * @description The oldest unpaid or partial month and what's left on it; otherwise the current month
         *     and its fee.
         */
        get: operations["suggestPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Payments
         * @description Every payment matching the filters, with the student's name.
         */
        get: operations["listPayments"];
        put?: never;
        /** Create Payment */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        /** Delete Payment */
        delete: operations["deletePayment"];
        options?: never;
        head?: never;
        /**
         * Update Payment
         * @description Partial update. Only fields that are sent change.
         */
        patch: operations["updatePayment"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Summary, yet-to-pay, backlog and overpaid lists for one month.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacklogItem
         * @description A student with Unpaid or Partial months before M.
         */
        BacklogItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Months
             * @description Oldest first.
             */
            months: components["schemas"]["BacklogMonth"][];
            /**
             * Total Owed Paise
             * @description Amount in paise, more than 0.
             */
            total_owed_paise: number;
        };
        /** BacklogMonth */
        BacklogMonth: {
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Amount in paise, 0 or more.
             */
            paid_paise: number;
            /**
             * Remaining Paise
             * @description Amount in paise, more than 0.
             */
            remaining_paise: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unpaid" | "partial";
        };
        /**
         * BalanceStatus
         * @description Overall standing of a student (PRD "Ledger rules", rule 6).
         * @enum {string}
         */
        BalanceStatus: "up_to_date" | "owes" | "credit";
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            summary: components["schemas"]["DashboardSummary"];
            /** Yet To Pay */
            yet_to_pay: components["schemas"]["YetToPayItem"][];
            /** Backlog */
            backlog: components["schemas"]["BacklogItem"][];
            /** Overpaid */
            overpaid: components["schemas"]["OverpaidItem"][];
        };
        /** DashboardSummary */
        DashboardSummary: {
            /**
             * Expected Paise
             * @description Expected for M from active students.
             */
            expected_paise: number;
            /**
             * Collected Paise
             * @description Payments whose for_month is M.
             */
            collected_paise: number;
            /**
             * Still Due Paise
             * @description Sum of max(0, expected - paid).
             */
            still_due_paise: number;
            /**
             * Not Fully Paid Count
             * @description Students unpaid or partial for M.
             */
            not_fully_paid_count: number;
            /**
             * Active Student Count
             * @description Students active in M.
             */
            active_student_count: number;
        };
        /**
         * ErrorResponse
         * @description Error body for 404 (and other non-validation errors): `detail` is a sentence.
         *
         *     422 responses use FastAPI's `HTTPValidationError` instead, where `detail` is a list of
         *     `{loc, msg, type}` items. Business-rule 422s raised by routers use the same list shape (see
         *     `app.errors.unprocessable`), so the UI handles one 422 format.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** FeeChangeRead */
        FeeChangeRead: {
            /** Id */
            id: number;
            /**
             * Effective Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            effective_month: string;
            /**
             * Amount Paise
             * @description Amount in paise, 0 or more.
             */
            amount_paise: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * App
             * @constant
             */
            app: "scrappy-records";
            /**
             * Version
             * @example 0.1.0
             */
            version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * LedgerMonth
         * @description One row of a student's month-by-month ledger.
         */
        LedgerMonth: {
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Amount in paise, 0 or more.
             */
            paid_paise: number;
            /**
             * Remaining Paise
             * @description max(0, expected - paid)
             */
            remaining_paise: number;
            /**
             * Excess Paise
             * @description max(0, paid - expected)
             */
            excess_paise: number;
            status: components["schemas"]["MonthStatus"];
            /**
             * Is Due
             * @description True for months up to and including the current month. Payments for later months are 'paid ahead'.
             */
            is_due: boolean;
        };
        /**
         * MonthStatus
         * @description Status of one student for one month (PRD "Ledger rules", rule 4).
         * @enum {string}
         */
        MonthStatus: "paid" | "partial" | "unpaid" | "overpaid" | "not_applicable";
        /**
         * OverpaidItem
         * @description A student-month up to M where paid > expected.
         */
        OverpaidItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /**
             * Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            month: string;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Amount in paise, more than 0.
             */
            paid_paise: number;
            /**
             * Excess Paise
             * @description Amount in paise, more than 0.
             */
            excess_paise: number;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Student Id */
            student_id: number;
            /**
             * Amount Paise
             * @description Amount in paise, more than 0.
             */
            amount_paise: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * For Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            for_month: string;
            method: components["schemas"]["PaymentMethod"];
            /** Note */
            note?: string | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "upi" | "cash" | "other";
        /** PaymentRead */
        PaymentRead: {
            /** Id */
            id: number;
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /**
             * Amount Paise
             * @description Amount in paise, more than 0.
             */
            amount_paise: number;
            /**
             * Paid On
             * Format: date
             */
            paid_on: string;
            /**
             * For Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            for_month: string;
            method: components["schemas"]["PaymentMethod"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
        };
        /**
         * PaymentSort
         * @enum {string}
         */
        PaymentSort: "paid_on" | "for_month" | "amount" | "student" | "method";
        /**
         * PaymentUpdate
         * @description Partial update. Only fields that are sent change.
         */
        PaymentUpdate: {
            /** Student Id */
            student_id?: number | null;
            /** Amount Paise */
            amount_paise?: number | null;
            /** Paid On */
            paid_on?: string | null;
            /** For Month */
            for_month?: string | null;
            method?: components["schemas"]["PaymentMethod"] | null;
            /** Note */
            note?: string | null;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** StudentCreate */
        StudentCreate: {
            /** Name */
            name: string;
            /**
             * Monthly Fee Paise
             * @description Amount in paise, 0 or more.
             */
            monthly_fee_paise: number;
            /**
             * Joined Month
             * @description First month they owe.
             * @example 2026-10
             */
            joined_month: string;
            /** Phone */
            phone?: string | null;
            /** Guardian Name */
            guardian_name?: string | null;
            /** Batch Label */
            batch_label?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Left Month
             * @description Last month they owe. Setting it archives the student.
             */
            left_month?: string | null;
        };
        /** StudentDetail */
        StudentDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Guardian Name */
            guardian_name: string | null;
            /** Batch Label */
            batch_label: string | null;
            /**
             * Joined Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            joined_month: string;
            /** Left Month */
            left_month: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Is Active
             * @description False once the student is archived (has left).
             */
            is_active: boolean;
            /**
             * Monthly Fee Paise
             * @description Fee in effect this month.
             */
            monthly_fee_paise: number;
            /**
             * Balance Paise
             * @description All payments minus everything expected up to this month. Negative means they owe; positive means credit.
             */
            balance_paise: number;
            status: components["schemas"]["BalanceStatus"];
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
            /**
             * Fee History
             * @description Oldest first.
             */
            fee_history: components["schemas"]["FeeChangeRead"][];
            /**
             * Months
             * @description From joined_month to the current month (or the last paid month, if later). Oldest first.
             */
            months: components["schemas"]["LedgerMonth"][];
            /** Payment Count */
            payment_count: number;
            /**
             * Total Paid Paise
             * @description Amount in paise, 0 or more.
             */
            total_paid_paise: number;
        };
        /**
         * StudentListFilter
         * @description `status` filter for `GET /api/students`. `left` means archived.
         * @enum {string}
         */
        StudentListFilter: "active" | "left" | "all";
        /**
         * StudentRead
         * @description A student as shown in lists, with their current fee and overall balance.
         */
        StudentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Guardian Name */
            guardian_name: string | null;
            /** Batch Label */
            batch_label: string | null;
            /**
             * Joined Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            joined_month: string;
            /** Left Month */
            left_month: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Is Active
             * @description False once the student is archived (has left).
             */
            is_active: boolean;
            /**
             * Monthly Fee Paise
             * @description Fee in effect this month.
             */
            monthly_fee_paise: number;
            /**
             * Balance Paise
             * @description All payments minus everything expected up to this month. Negative means they owe; positive means credit.
             */
            balance_paise: number;
            status: components["schemas"]["BalanceStatus"];
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp, e.g. 2026-10-05T09:30:00Z
             */
            updated_at: string;
        };
        /**
         * StudentUpdate
         * @description Partial update. Only fields that are sent change.
         *
         *     To change the fee, send `monthly_fee_paise`, and optionally `fee_effective_month` (defaults
         *     to the current month). Earlier months keep their old fee. Send `left_month: null` to
         *     un-archive a student.
         *
         *     Edit rules. This model checks what it can on its own. The router checks the rest against the
         *     stored student and answers **422** in the standard validation shape (`app.errors`), never a
         *     500 from a database CHECK:
         *
         *     1. **Moving `joined_month`** moves the earliest fee change's `effective_month` with it, so
         *        the first owed month always has a fee. If the new joined month is on or after a later
         *        fee change, answer 422, because the earliest fee would disappear.
         *     2. **`fee_effective_month` before `joined_month`** (the new one if sent, else the stored
         *        one) → 422. A fee change for a month that already has one replaces its amount.
         *     3. **`left_month`** is checked against `joined_month` (the new one if sent, else the
         *        stored one): `left_month < joined_month` → 422.
         */
        StudentUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Guardian Name */
            guardian_name?: string | null;
            /** Batch Label */
            batch_label?: string | null;
            /** Notes */
            notes?: string | null;
            /** Joined Month */
            joined_month?: string | null;
            /** Left Month */
            left_month?: string | null;
            /** Monthly Fee Paise */
            monthly_fee_paise?: number | null;
            /**
             * Fee Effective Month
             * @description Month the new fee starts. Only with monthly_fee_paise. Defaults to now.
             */
            fee_effective_month?: string | null;
        };
        /**
         * SuggestedPayment
         * @description Prefill for the Log payment form: the oldest unpaid or partial month and what's left on
         *     it, otherwise the current month and its fee.
         */
        SuggestedPayment: {
            /**
             * For Month
             * @description A month as "YYYY-MM".
             * @example 2026-10
             */
            for_month: string;
            /**
             * Amount Paise
             * @description Amount in paise, 0 or more.
             */
            amount_paise: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * YetToPayItem
         * @description A student active in M who is Unpaid or Partial for M.
         */
        YetToPayItem: {
            /** Student Id */
            student_id: number;
            /** Student Name */
            student_name: string;
            /** Batch Label */
            batch_label: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Expected Paise
             * @description Amount in paise, 0 or more.
             */
            expected_paise: number;
            /**
             * Paid Paise
             * @description Amount in paise, 0 or more.
             */
            paid_paise: number;
            /**
             * Remaining Paise
             * @description Amount in paise, more than 0.
             */
            remaining_paise: number;
            /**
             * Status
             * @enum {string}
             */
            status: "unpaid" | "partial";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type BacklogItem = components['schemas']['BacklogItem'];
export type BacklogMonth = components['schemas']['BacklogMonth'];
export type BalanceStatus = components['schemas']['BalanceStatus'];
export type DashboardResponse = components['schemas']['DashboardResponse'];
export type DashboardSummary = components['schemas']['DashboardSummary'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type FeeChangeRead = components['schemas']['FeeChangeRead'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type LedgerMonth = components['schemas']['LedgerMonth'];
export type MonthStatus = components['schemas']['MonthStatus'];
export type OverpaidItem = components['schemas']['OverpaidItem'];
export type PaymentCreate = components['schemas']['PaymentCreate'];
export type PaymentMethod = components['schemas']['PaymentMethod'];
export type PaymentRead = components['schemas']['PaymentRead'];
export type PaymentSort = components['schemas']['PaymentSort'];
export type PaymentUpdate = components['schemas']['PaymentUpdate'];
export type SortOrder = components['schemas']['SortOrder'];
export type StudentCreate = components['schemas']['StudentCreate'];
export type StudentDetail = components['schemas']['StudentDetail'];
export type StudentListFilter = components['schemas']['StudentListFilter'];
export type StudentRead = components['schemas']['StudentRead'];
export type StudentUpdate = components['schemas']['StudentUpdate'];
export type SuggestedPayment = components['schemas']['SuggestedPayment'];
export type ValidationError = components['schemas']['ValidationError'];
export type YetToPayItem = components['schemas']['YetToPayItem'];
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listStudents: {
        parameters: {
            query?: {
                /** @description `active` (default), `left` (archived) or `all`. */
                status?: components["schemas"]["StudentListFilter"];
                /** @description Case-insensitive search on name, phone, guardian. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedPayment"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPayments: {
        parameters: {
            query?: {
                /** @description Only this student's payments. */
                student_id?: number | null;
                /** @description Only payments for this month (`for_month`). */
                month?: string | null;
                /** @description Case-insensitive search on student name and note. */
                q?: string | null;
                sort?: components["schemas"]["PaymentSort"];
                order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No student with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description No payment with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                /** @description Defaults to the current month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
