"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 19:56:34.818058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("guardian_name", sa.String(), nullable=True),
        sa.Column("batch_label", sa.String(), nullable=True),
        sa.Column("joined_month", sa.Date(), nullable=False),
        sa.Column("left_month", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "CAST(strftime('%d', joined_month) AS INTEGER) = 1",
            name=op.f("ck_students_joined_month_first_of_month"),
        ),
        sa.CheckConstraint(
            "left_month IS NULL OR CAST(strftime('%d', left_month) AS INTEGER) = 1",
            name=op.f("ck_students_left_month_first_of_month"),
        ),
        sa.CheckConstraint(
            "left_month IS NULL OR left_month >= joined_month",
            name=op.f("ck_students_left_after_joined"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_students_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_index("ix_students_name", ["name"], unique=False)

    op.create_table(
        "fee_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("effective_month", sa.Date(), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "CAST(strftime('%d', effective_month) AS INTEGER) = 1",
            name=op.f("ck_fee_changes_effective_month_first_of_month"),
        ),
        sa.CheckConstraint("amount_paise >= 0", name=op.f("ck_fee_changes_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_fee_changes_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_changes")),
        sa.UniqueConstraint(
            "student_id", "effective_month", name=op.f("uq_fee_changes_student_id_effective_month")
        ),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=False),
        sa.Column("for_month", sa.Date(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("upi", "cash", "other", name="payment_method", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "CAST(strftime('%d', for_month) AS INTEGER) = 1",
            name=op.f("ck_payments_for_month_first_of_month"),
        ),
        sa.CheckConstraint(
            "method IN ('upi', 'cash', 'other')", name=op.f("ck_payments_method_valid")
        ),
        sa.CheckConstraint("amount_paise > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_payments_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_for_month", ["for_month"], unique=False)
        batch_op.create_index("ix_payments_paid_on", ["paid_on"], unique=False)
        batch_op.create_index(
            "ix_payments_student_id_for_month", ["student_id", "for_month"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index("ix_payments_student_id_for_month")
        batch_op.drop_index("ix_payments_paid_on")
        batch_op.drop_index("ix_payments_for_month")

    op.drop_table("payments")
    op.drop_table("fee_changes")
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_index("ix_students_name")

    op.drop_table("students")
    # ### end Alembic commands ###
